version: "3.9"
services:
  www:
    build:
      context: ..
      dockerfile: ./docker/www/Dockerfile

    ports:
      - 80:80
      - 443:443

    environment:
      CERTBOT_EMAIL: "sami.guiderdoni@gmail.com"

    volumes:
      - letsencrypt:/etc/letsencrypt

    container_name: www

volumes:
  letsencrypt: